{% set name = "impl" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/josharian/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fcc2344f5386583a2cfda9b0830e347eb6e8b946c0b3e3260bbb4b8479eb2c25

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - {{ name }} --help 2>&1 | grep -q "impl generates method stubs for recv to implement iface"

about:
  home: https://github.com/josharian/{{ name }}
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: impl generates method stubs for implementing an interface
  dev_url: https://github.com/josharian/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
